export const categoryCollection = [
  {
    id: "c1",
    category: "chair",
    name: "Irani Chair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "5x4 ft",
    rating: 4,
    reviews: 144,
    color: "orange & white",
    price: 144,

    // img: Chair1,
    offer: null,
  },
  {
    id: "c2",
    category: "chair",
    name: "Modern Chair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "UAE",
    size: "5x5 ft",
    rating: 3.5,
    reviews: 100,
    color: "white",
    price: 150,

    // img: Chair3,
    offer: 11,
  },
  {
    id: "c3",
    category: "chair",
    name: "Russian Sofa-chair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Russia",
    size: "4x3 ft",
    rating: 5,
    reviews: 200,
    color: "white",
    price: 80,

    // img: Chair4,
    offer: 16,
  },
  {
    id: "b1",
    category: "bed",
    name: "Soft Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Russia",
    size: "2x14 ft",
    rating: 4.5,
    reviews: 20,
    color: "brown",
    price: 150,

    // img: Bed1,
    offer: 16,
  },
  {
    id: "b2",
    category: "bed",
    name: "Lumani Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Russia",
    size: "3x9 ft",
    rating: 4.3,
    reviews: 200,
    color: "black",
    price: 150,

    // img: Bed2,
    offer: 16,
  },
  {
    id: "b3",
    category: "bed",
    name: "Bed Rest American",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "USA",
    size: "1x10 ft",
    rating: 5,
    reviews: 350,
    color: "white",
    price: 190,

    // img: Bed3,
    offer: 16,
  },
  {
    id: "b4",
    category: "bed",
    name: "Golden Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "South Africa",
    size: "1x10 ft",
    rating: 3.8,
    reviews: 150,
    color: "golden-black",
    price: 300,

    // img: Bed4,
    offer: 16,
  },
  {
    id: "b5",
    category: "bed",
    name: "Tiger Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Nepal",
    size: "1x10 ft",
    rating: 4,
    reviews: 80,
    color: "brown-black",
    price: 100,

    // img: Bed5,
    offer: 16,
  },
  {
    id: "cl1",
    category: "shirt",
    name: "Shirt Gucci",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Ireland",
    size: "xl",
    rating: 5,
    reviews: 700,
    color: "black",
    price: 20,

    // img: Cloth1,
    offer: 16,
  },
  {
    id: "cl2",
    category: "pant",
    name: "Dress Pant",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Ireland",
    size: "md",
    rating: 4.8,
    reviews: 400,
    color: "sky-blue",
    price: 30,

    // img: Cloth2,
    offer: 16,
  },
  {
    id: "pr1",
    category: "perfume",
    name: "J. Rose",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Pakistan",
    size: "4 inches",
    rating: 5,
    reviews: 600,
    color: "red",
    price: 122,

    // img: Perfume1,
    offer: 16,
  },
  {
    id: "pr2",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    price: 50,

    // img: Perfume2,
    offer: 16,
  },
  {
    id: "pr3",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    price: 50,

    // img: Perfume3,
    offer: 16,
  },
  {
    id: "pr4",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    price: 50,

    // img: Perfume4,
    offer: 16,
  },
  {
    id: "pr5",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    price: 50,

    // img: Perfume5,
    offer: 16,
  },
  {
    id: "sh1",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    price: 50,

    // img: Shoes1,
    offer: 16,
  },
  {
    id: "sh2",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    price: 50,

    // img: Shoes2,
    offer: 16,
  },
  {
    id: "sh3",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    price: 50,

    // img: Shoes3,
    offer: 16,
  },
  {
    id: "sh4",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    price: 50,

    // img: Shoes4,
    offer: 16,
  },
  {
    id: "sh5",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    price: 50,

    // img: Shoes5,
    offer: 16,
  },
  {
    id: "tb1",
    category: "table",
    name: "Dining Table",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "5x12 ft",
    rating: 5,
    reviews: 367,
    color: "off-white",
    price: 200,

    // img: Table1,
    offer: 16,
  },
  {
    id: "tb2",
    category: "table",
    name: "Dining Table",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "5x12 ft",
    rating: 5,
    reviews: 367,
    color: "orange",
    price: 200,

    // img: Table2,
    offer: 16,
  },
  {
    id: "tb3",
    category: "table",
    name: "Dining Table",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "5x12 ft",
    rating: 5,
    reviews: 367,
    color: "black",
    price: 200,

    // img: Table3,
    offer: 16,
  },
  {
    id: "w1",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "golden-blue",
    price: 2000,

    // img: Watch1,
    offer: 16,
  },
  {
    id: "w2",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "white-orange",
    price: 2000,

    // img: Watch2,
    offer: 16,
  },
  {
    id: "w3",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "white-black",
    price: 2000,

    // img: Watch3,
    offer: 16,
  },
  {
    id: "w4",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "golden-black",
    price: 2000,

    // img: Watch4,
    offer: 16,
  },
  {
    id: "w5",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "white-orange",
    price: 6000,

    // img: Watch5,
    offer: 16,
  },
  {
    id: "w6",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "golden-blue",
    price: 2000,

    // img: Watch6,
    offer: 16,
  },
];
