import Bed1 from "../../assets/bed1.jpg";
import Bed2 from "../../assets/bed2.jpg";
import Bed3 from "../../assets/bed3.jpg";
import Bed4 from "../../assets/bed4.jpg";
import Bed5 from "../../assets/bed5.jpg";

import Chair1 from "../../assets/chair1.jpg";
import Chair3 from "../../assets/chair3.jpg";
import Chair4 from "../../assets/chair4.jpg";

import Cloth1 from "../../assets/cloth1.jpg";
import Cloth2 from "../../assets/cloth3.jpg";

import Perfume1 from "../../assets/perfume1.jpg";
import Perfume2 from "../../assets/perfume2.jpg";
import Perfume3 from "../../assets/perfume3.jpg";
import Perfume4 from "../../assets/perfume4.jpg";
import Perfume5 from "../../assets/perfume5.jpg";

import Shoes1 from "../../assets/shoes1.jpg";
import Shoes2 from "../../assets/shoes2.jpg";
import Shoes3 from "../../assets/shoes3.jpg";
import Shoes4 from "../../assets/shoes4.jpg";
import Shoes5 from "../../assets/shoes5.jpg";

import Table1 from "../../assets/table1.jpg";
import Table2 from "../../assets/table2.jpg";
import Table3 from "../../assets/table3.jpg";

import Watch1 from "../../assets/watch1.jpg";
import Watch2 from "../../assets/watch2.jpg";
import Watch3 from "../../assets/watch3.jpg";
import Watch4 from "../../assets/watch4.jpg";
import Watch5 from "../../assets/watch5.jpg";
import Watch6 from "../../assets/watch6.jpg";

export const categoryCollection = [
  {
    id: "c1",
    category: "chair",
    name: "Irani Chair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "5x4 ft",
    rating: 4,
    reviews: 144,
    color: "orange & white",
    minPrice: 144,
    maxPrice: 150,
    img: Chair1,
    offer: "16% OFF",
  },
  {
    id: "c2",
    category: "chair",
    name: "Modern Chair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "UAE",
    size: "5x5 ft",
    rating: 3.5,
    reviews: 100,
    color: "white",
    minPrice: 100,
    maxPrice: 105,
    img: Chair3,
    offer: "16% OFF",
  },
  {
    id: "c3",
    category: "chair",
    name: "Russian Sofa-chair",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Russia",
    size: "4x3 ft",
    rating: 5,
    reviews: 200,
    color: "white",
    minPrice: 80,
    maxPrice: 95,
    img: Chair4,
    offer: "16% OFF",
  },
  {
    id: "b1",
    category: "bed",
    name: "Soft Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Russia",
    size: "2x14 ft",
    rating: 4.5,
    reviews: 20,
    color: "brown",
    minPrice: 150,
    maxPrice: 200,
    img: Bed1,
    offer: "16% OFF",
  },
  {
    id: "b2",
    category: "bed",
    name: "Lumani Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Russia",
    size: "3x9 ft",
    rating: 4.3,
    reviews: 200,
    color: "black",
    minPrice: 150,
    maxPrice: 200,
    img: Bed2,
    offer: "16% OFF",
  },
  {
    id: "b3",
    category: "bed",
    name: "Bed Rest American",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "USA",
    size: "1x10 ft",
    rating: 5,
    reviews: 350,
    color: "white",
    minPrice: 190,
    maxPrice: 200,
    img: Bed3,
    offer: "16% OFF",
  },
  {
    id: "b4",
    category: "bed",
    name: "Golden Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "South Africa",
    size: "1x10 ft",
    rating: 3.8,
    reviews: 150,
    color: "golden-black",
    minPrice: 300,
    maxPrice: 310,
    img: Bed4,
    offer: "16% OFF",
  },
  {
    id: "b5",
    category: "bed",
    name: "Tiger Bed",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Nepal",
    size: "1x10 ft",
    rating: 4,
    reviews: 80,
    color: "brown-black",
    minPrice: 100,
    maxPrice: 150,
    img: Bed5,
    offer: "16% OFF",
  },
  {
    id: "cl1",
    category: "shirt",
    name: "Shirt Gucci",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Ireland",
    size: "xl",
    rating: 5,
    reviews: 700,
    color: "black",
    minPrice: 20,
    maxPrice: 22,
    img: Cloth1,
    offer: "16% OFF",
  },
  {
    id: "cl2",
    category: "pant",
    name: "Dress Pant",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Ireland",
    size: "md",
    rating: 4.8,
    reviews: 400,
    color: "sky-blue",
    minPrice: 30,
    maxPrice: 31,
    img: Cloth2,
    offer: "16% OFF",
  },
  {
    id: "pr1",
    category: "perfume",
    name: "J. Rose",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Pakistan",
    size: "4 inches",
    rating: 5,
    reviews: 600,
    color: "red",
    minPrice: 122,
    maxPrice: 130,
    img: Perfume1,
    offer: "16% OFF",
  },
  {
    id: "pr2",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    minPrice: 50,
    maxPrice: 70,
    img: Perfume2,
    offer: "16% OFF",
  },
  {
    id: "pr3",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    minPrice: 50,
    maxPrice: 70,
    img: Perfume3,
    offer: "16% OFF",
  },
  {
    id: "pr4",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    minPrice: 50,
    maxPrice: 70,
    img: Perfume4,
    offer: "16% OFF",
  },
  {
    id: "pr5",
    category: "perfume",
    name: "Rose Marry",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "China",
    size: "4.6 inches",
    rating: 5,
    reviews: 100,
    color: "yellow",
    minPrice: 50,
    maxPrice: 70,
    img: Perfume5,
    offer: "16% OFF",
  },
  {
    id: "sh1",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    minPrice: 50,
    maxPrice: 70,
    img: Shoes1,
    offer: "16% OFF",
  },
  {
    id: "sh2",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    minPrice: 50,
    maxPrice: 70,
    img: Shoes2,
    offer: "16% OFF",
  },
  {
    id: "sh3",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    minPrice: 50,
    maxPrice: 70,
    img: Shoes3,
    offer: "16% OFF",
  },
  {
    id: "sh4",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    minPrice: 50,
    maxPrice: 70,
    img: Shoes4,
    offer: "16% OFF",
  },
  {
    id: "sh5",
    category: "shoes",
    name: "Iranian",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "Iran",
    size: "9 inches",
    rating: 5,
    reviews: 100,
    color: "orange",
    minPrice: 50,
    maxPrice: 70,
    img: Shoes5,
    offer: "16% OFF",
  },
  {
    id: "tb1",
    category: "table",
    name: "Dining Table",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "5x12 ft",
    rating: 5,
    reviews: 367,
    color: "off-white",
    minPrice: 200,
    maxPrice: 220,
    img: Table1,
    offer: "16% OFF",
  },
  {
    id: "tb2",
    category: "table",
    name: "Dining Table",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "5x12 ft",
    rating: 5,
    reviews: 367,
    color: "orange",
    minPrice: 200,
    maxPrice: 220,
    img: Table2,
    offer: "16% OFF",
  },
  {
    id: "tb3",
    category: "table",
    name: "Dining Table",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "5x12 ft",
    rating: 5,
    reviews: 367,
    color: "black",
    minPrice: 200,
    maxPrice: 220,
    img: Table3,
    offer: "16% OFF",
  },
  {
    id: "w1",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "golden-blue",
    minPrice: 2000,
    maxPrice: 6000,
    img: Watch1,
    offer: "16% OFF",
  },
  {
    id: "w2",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "white-orange",
    minPrice: 2000,
    maxPrice: 6000,
    img: Watch2,
    offer: "16% OFF",
  },
  {
    id: "w3",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "white-black",
    minPrice: 2000,
    maxPrice: 6000,
    img: Watch3,
    offer: "16% OFF",
  },
  {
    id: "w4",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "golden-black",
    minPrice: 2000,
    maxPrice: 6000,
    img: Watch4,
    offer: "16% OFF",
  },
  {
    id: "w5",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "white-orange",
    minPrice: 2000,
    maxPrice: 6000,
    img: Watch5,
    offer: "16% OFF",
  },
  {
    id: "w6",
    category: "watch",
    name: "Rollex Special",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium minima eaque, labore esse minus ad accusamus soluta! Quia, sapiente iure tempora iusto quos laborum ipsa.",
    country: "America",
    size: "1x0.2 inches",
    rating: 5,
    reviews: 2000,
    color: "golden-blue",
    minPrice: 2000,
    maxPrice: 6000,
    img: Watch6,
    offer: "16% OFF",
  },
];
